"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_loss.ipynb.

# %% auto 0
__all__ = ['FocalLoss', 'get_cls', 'get_cb_weights', 'init_loss']

# %% ../nbs/03_loss.ipynb 3
import torch
import torch.nn as nn
import torch.nn.functional as F

class FocalLoss(nn.Module):
    def __init__(self, gamma=2, alpha=0.25, reduction='mean'):
        super(FocalLoss, self).__init__()
        self.gamma = gamma
        self.reduction = reduction

        if isinstance(alpha, (float, int)):
            self.register_buffer('alpha', torch.tensor([alpha]))
        else:
            self.register_buffer('alpha', torch.tensor(alpha))

    def forward(self, inputs, targets):
        bce_loss = F.binary_cross_entropy_with_logits(inputs, targets, reduction='none')
        p_t = torch.exp(-bce_loss)
        focal_weight = (1 - p_t) ** self.gamma
        alpha = self.alpha.to(inputs.device)

        alpha_t = alpha * targets + (1 - alpha) * (1 - targets)
        
        loss = alpha_t * focal_weight * bce_loss
        if self.reduction == 'mean':
            return loss.mean()
        elif self.reduction == 'sum':
            return loss.sum()
        else:
            return loss
        

# %% ../nbs/03_loss.ipynb 4
import importlib
def get_cls(module_name, class_name):
    module = importlib.import_module(module_name)
    return getattr(module, class_name)

# %% ../nbs/03_loss.ipynb 5
import numpy as np

def get_cb_weights(labels_count_list, beta=0.999):
    effective_num = 1.0 - np.power(beta, labels_count_list)
    weights = (1.0 - beta) / np.array(effective_num)
    
    weights = weights / np.sum(weights) * len(labels_count_list)
    return torch.tensor(weights, dtype=torch.float32)



# %% ../nbs/03_loss.ipynb 8
def init_loss(cfg, weights = [517, 163, 142], device='cuda'):
    
    if cfg.loss.name == "BCEWithLogitsLoss":
        return torch.nn.BCEWithLogitsLoss()
    
    alpha, gamma = cfg.loss.params.get("alpha", None), cfg.loss.params.get("gamma", None)
    if cfg.loss.name == "BalancedFocalLoss":
        alpha = get_cb_weights(weights)
        cfg.loss.name = "FocalLoss"

    loss_cls = get_cls("dl.loss", cfg.loss.name)
    loss = loss_cls(alpha=alpha, gamma=gamma).to(device)
    cfg.loss.name == "BalancedFocalLoss"
    return loss
