# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/image-retina-project',
                'doc_host': 'https://Ahmed-Khaled-Saleh.github.io',
                'git_url': 'https://github.com/Ahmed-Khaled-Saleh/image-retina-project',
                'lib_path': 'image_retina_project'},
  'syms': {'image_retina_project.core': {'image_retina_project.core.foo': ('core.html#foo', 'image_retina_project/core.py')}}}
