project_name: Task_1_finetuning
task: probing
epochs: 300

root_dir: /scratch/project_2009050/
save_dir : models
res_dir: results
log_dir: ../logs

data:
  name: RetinaMultiLabelDataset
  data_root: /scratch/project_2009050/final_project_resources
  batch_size: 512
  V: 1
  label_names: ['DR', 'Glaucoma', 'AMD']
  img_size: 256


model:
  backbone: efficientnet
  pretrained: true
  ckpt: /scratch/project_2009050/final_project_resources/pretrained_backbone/ckpt_efficientnet_ep50.pt


optimizer:
  name: Adam
  lr: 0.0001